server:
  port: 8085


spring: 
  thymeleaf:
    check-template: false
    check-template-location: false
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: ingredientService
        uri: http://ingredient-service/
        predicates:
        - Path=/ingredients/**    
